import ClimaCore: InputOutput
import ClimaUtilities.OutputPathGenerator
import ClimaUtilities.TimeManager: ITime

#####
##### Restart file loading + output directory resolution.
#####

"""
    get_state_restart(restart_file, start_date, model::AtmosModel, comms_ctx)

Read the state and start time from an HDF5 restart file.

Warns when the file records a different physics hash than `hash_physics(model)`,
since the restart is then not guaranteed to be compatible. The hash covers the
physics fields only: the grid is checked separately by the caller, and the
setup and params do not affect whether a checkpoint can be resumed.

# Returns

`(Y, t_start)`: the state vector and the restart time as an `ITime` with epoch
`start_date`.
"""
function get_state_restart(
    restart_file,
    start_date,
    model::AtmosModel,
    comms_ctx,
)
    @assert !isnothing(restart_file)
    atmos_model_hash = hash_physics(model)
    reader = InputOutput.HDF5Reader(restart_file, comms_ctx)
    Y = InputOutput.read_field(reader, "Y")
    # TODO: Do not use InputOutput.HDF5 directly
    t_start = InputOutput.HDF5.read_attribute(reader.file, "time")
    t_start = ITime(t_start; epoch = start_date)
    if "atmos_model_hash" in keys(InputOutput.HDF5.attrs(reader.file))
        atmos_model_hash_in_restart =
            InputOutput.HDF5.read_attribute(reader.file, "atmos_model_hash")
        if atmos_model_hash_in_restart != atmos_model_hash
            @warn "Restart file $(restart_file) was constructed with a different AtmosModel"
        end
    end
    return (Y, t_start)
end

"""
    handle_restart(restart_file, t_start_original, start_date, model, context; verbose = false)

Load a restart file, warning when a nonzero `t_start_original` is passed, since the
restart time from the file takes precedence.

# Returns

`(Y, t_start, spaces)`:

  - `Y`: State loaded from the restart file.
  - `t_start`: Restart time as an `ITime` with epoch `start_date` [s].
  - `spaces`: `(; center_space, face_space)` taken from `Y`.
"""
function handle_restart(
    restart_file,
    t_start_original,
    start_date,
    model,
    context;
    verbose = false,
)
    # Validate t_start before restart (matches get_simulation behavior)
    t_start_seconds = time_to_seconds(t_start_original)
    if t_start_seconds != 0
        @warn "Non zero `t_start` passed with a restarting simulation. The provided `t_start` will be ignored."
    end

    (Y, t_start) = get_state_restart(restart_file, start_date, model, context)

    if verbose
        @info "Restarting simulation from file" restart_file restart_time =
            string(t_start)
    end

    spaces = (; center_space = axes(Y.c), face_space = axes(Y.f))

    return Y, t_start, spaces
end

"""
    auto_detect_restart_file(::OutputPathGenerator.OutputPathGeneratorStyle, base_output_dir)

Fallback method that errors: automatic restart detection requires the active-link output
directory style.
"""
auto_detect_restart_file(::OutputPathGenerator.OutputPathGeneratorStyle, _) =
    error("auto_detect_restart_file works only with ActiveLink")

"""
    auto_detect_restart_file(::ActiveLinkStyle, base_output_dir)

Return the most recent restart file in the directory structure in `base_output_dir`, if any.

`auto_detect_restart_file` scans the content of `base_output_dir` matching the expected
names for output folders generated by `ActiveLinkStyle` (e.g., `output_0000`, `output_0001`).
It iterates through these folders sorted by number in descending order and returns the latest
restart file (latest measured by the time in the file name) from the first folder that contains
restart files matching the pattern `dayDDDD.SSSSS.hdf5`. This ensures that empty or incomplete
higher-numbered folders are skipped in favor of folders that actually contain restart files.
If no folder with restart files is found, return `nothing`: this means that the simulation
cannot be automatically restarted.
"""
function auto_detect_restart_file(
    ::OutputPathGenerator.ActiveLinkStyle,
    base_output_dir,
)
    # if base_output_dir does not exist, we return restart_file = nothing because there is
    # no restart file to be detected
    isdir(base_output_dir) || return nothing

    # output_dir will be something like ABC/DEF/output_1234
    name_rx = r"output_(\d\d\d\d)"
    restart_file_rx = r"day\d+\.\w+\.hdf5"
    restart_file = nothing

    existing_outputs =
        filter(x -> !isnothing(match(name_rx, x)), readdir(base_output_dir))

    isempty(existing_outputs) && return nothing

    # Sort folders by number (descending) and find the first with restart files
    for output_folder in sort(existing_outputs, rev = true)
        folder_path = joinpath(base_output_dir, output_folder)
        possible_restart_files =
            filter(f -> occursin(restart_file_rx, f), readdir(folder_path))
        if !isempty(possible_restart_files)
            previous_folder = folder_path
            restart_file_name = last(sort_files_by_time(possible_restart_files))
            restart_file = joinpath(previous_folder, restart_file_name)
            @assert isfile(restart_file) "Restart file does not exist"
            return restart_file
        end
    end

    # No folder with restart files found
    @warn "No restart files found in any output folder in $(base_output_dir)"
    return nothing
end

"""
    setup_output_dir(job_id, output_dir, output_dir_style, detect_restart_file, restart_file, comms_ctx)

Create the output directory for a run and resolve which restart file, if any, to use.

The base directory is `output_dir` when given, and otherwise `output/<job_id>`, or just
`<job_id>` when the `CI` environment variable is set (as it is in our
continuous-integration system). `output_dir_style` is matched case-insensitively and must
be `"activelink"` (numbered `output_NNNN` directories with a symlink to the active one) or
`"removepreexisting"` (previous output is deleted); anything else raises an error. When
`detect_restart_file` is set and no `restart_file` was given, the most recent restart file
under the base directory is picked up by `auto_detect_restart_file`, which only works with
the active-link style.

# Returns

`(output_dir, restart_file)`: the generated output directory and the resolved restart
file, or `nothing` if there is none.
"""
function setup_output_dir(
    job_id,
    output_dir,
    output_dir_style,
    detect_restart_file,
    restart_file,
    comms_ctx,
)
    # Set up base output directory.
    # The `CI` environment variable (set by our continuous-integration system)
    # switches the default output location from `output/<job_id>` to `<job_id>`.
    default_output = haskey(ENV, "CI") ? job_id : joinpath("output", job_id)
    base_output_dir = isnothing(output_dir) ? default_output : output_dir

    # Validate and get output directory style
    allowed_dir_styles = Dict(
        "activelink" => OutputPathGenerator.ActiveLinkStyle(),
        "removepreexisting" => OutputPathGenerator.RemovePreexistingStyle(),
    )

    haskey(allowed_dir_styles, lowercase(output_dir_style)) ||
        error("output_dir_style $(output_dir_style) not available")

    output_dir_style_obj = allowed_dir_styles[lowercase(output_dir_style)]

    final_restart_file = if detect_restart_file && isnothing(restart_file)
        auto_detect_restart_file(output_dir_style_obj, base_output_dir)
    else
        restart_file
    end

    # Generate the actual output directory
    output_dir = OutputPathGenerator.generate_output_path(
        base_output_dir;
        context = comms_ctx,
        style = output_dir_style_obj,
    )

    return output_dir, final_restart_file
end
