initial_condition: "DryDensityCurrentProfile"
config: "box"
hyperdiff: ~
x_max: 12800.0
y_max: 12800.0
z_max: 6400.0
x_elem: 8
y_elem: 8
z_elem: 10
z_stretch: false
dt: "0.5secs"
t_end: "5secs"
dt_save_state_to_disk: "5secs"
disable_surface_flux_tendency: true
check_conservation: true
acoustic_substeps: "auto"
acoustic_substep_order: 2
acoustic_substep_damping: 1.5
acoustic_substep_implicit_split: true
