config: "plane"
FLOAT_TYPE: "Float32"
initial_condition: "ConstantBuoyancyFrequencyProfile"
topography: "Schar"
mesh_warp_type: "Linear"
x_max: 100e3
z_max: 21e3
x_elem: 100
z_elem: 100
dz_bottom: 10
dt: "10secs"
t_end: "1days"
rayleigh_sponge: true
#Implicit Solver 
fully_implicit: true
ode_algo: "ARS222" 
use_krylov_method: true
max_newton_iters_ode: 5
use_newton_rtol: true
newton_rtol: 1.0e-5
use_dynamic_krylov_rtol: true
krylov_rtol: 0.1
krylov_memory: 30
krylov_itmax: 150
# Fully Implicit
disable_surface_flux_tendency: true
toml: [toml/steady_state_test.toml]
check_steady_state: true
output_default_diagnostics: false
diagnostics:
  - short_name: [orog, ua, wa, uapredicted, wapredicted, uaerror, waerror]
    period: 1hours
