initial_condition: "Rico"
turbconv: "prognostic_edmfx"
reproducibility_test: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
prognostic_tke: true
update_cache_every: "step"
microphysics_model: "1M"
config: "column"
z_max: 4e3
x_elem: 2
y_elem: 2
z_elem: 100
z_stretch: false
perturb_initstate: false
dt: "120secs"
t_end: "24hours"
dt_save_state_to_disk: "60mins"
toml: [toml/prognostic_edmfx_1M.toml]
netcdf_interpolation_num_points: [8, 8, 100]
ode_algo: "ARS222"
