# ARM VARANAL SCM configuration
# Semi-continuous forcing from ARM Variational Analysis product
# Default site: SGP (Southern Great Plains)
initial_condition: "ARMVARANAL"
external_forcing: "ARMVARANAL"
armvaranal_case_name: "SGP_VARANAL"
# Monthly files from: https://adc.arm.gov/discovery/
external_forcing_file: "/net/sampo/data1/cchristo/ARM_data/arm_265588/sgp60varanarucC1.c1/sgp60varanarucC1.c1.20100801.000000.cdf"
turbconv: "prognostic_edmfx"
tracer_upwinding: first_order
implicit_diffusion: true
implicit_sgs_advection: true
implicit_sgs_entr_detr: true
implicit_sgs_nh_pressure: true
implicit_sgs_vertdiff: true
implicit_sgs_mass_flux: true
approximate_linear_solve_iters: 2
max_newton_iters_ode_subproblem: 0
max_newton_iters_ode: 3
rayleigh_sponge: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
prognostic_tke: true
microphysics_model: "0M"
config: "column"
hyperdiff: "false"
z_max: 15e3 # ARM VARANAL data extends to ~16 km (100 hPa).
z_elem: 45
z_stretch: true
dz_bottom: 30
perturb_initstate: false
dt: "80secs"
dt_rad: "120mins"
# t_end: "10days"
t_end: "4days"
dt_save_state_to_disk: "1000days"
ode_algo: "ARS222"
# toml: [toml/prognostic_edmfx_gcmdriven.toml]
toml: [toml/prognostic_edmfx_gcmdriven_saj_detr.toml]
rad: allskywithclear
insolation: "timevarying"
start_date: "20100801" # YYYYMMDD
# SGP site coordinates (for Coriolis, insolation calculations)
latitude: 36.61
longitude: -97.49
netcdf_output_at_levels: true
netcdf_interpolation_num_points: [2, 2, 60]
output_default_diagnostics: false
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr]
    period: 10mins
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, taen, thetaaen, haen, husen, huren, clwen, clien, tke]
    period: 10mins
  - short_name: [entr, detr, lmix, bgrad, strain, edt, evu, turbentr]
    period: 10mins
  - short_name: [rlut, rlutcs, rsut, rsutcs, rsds, rsus, rlds, rlus, clwvi, lwp, clivi, dsevi, clvi, prw, hurvi, husv]
    period: 10mins
  - reduction_time: max
    short_name: tke
    period: 10mins
