initial_condition: DYCOMS_RF01
turbconv: prognostic_edmfx
implicit_diffusion: true
approximate_linear_solve_iters: 2
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
prognostic_tke: true
microphysics_model: "1M"
config: column
hyperdiff: ~
z_max: 1500
x_elem: 2
y_elem: 2
z_elem: 30
z_stretch: false
dt: 120secs
t_end: 6hours
dt_save_state_to_disk: 10mins
toml: [toml/prognostic_edmfx_1M.toml]
netcdf_interpolation_num_points: [2, 2, 30]
ode_algo: "ARS222"
