# This job takes too long so we use a lower top and coarser vertical resolution
z_max: 30000.0
z_elem: 10
dz_bottom: 500.0
dt: 20secs
surface_setup: DefaultMoninObukhov
rad: clearsky
turbconv: prognostic_edmfx
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
implicit_diffusion: true
approximate_linear_solve_iters: 2
microphysics_model: "0M"
chemistry_model: "passive"
chemistry_config: "config/chemistry_configs/edde.yaml"
t_end: 1hours
dt_save_state_to_disk: 600secs
toml: [toml/prognostic_edmfx.toml]
output_default_diagnostics: false
reproducibility_test: true
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hfss, hfls, hur, hus, cl, clw, cli, evspsbl, pr, rsd, rsu, rld, rlu]
    reduction_time: average
    period: 1hours
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, tke, lmix, q_gas_E, q_gas_D, q_gas_ED, q_gas_Eup, q_gas_Dup, q_gas_EDup]
    reduction_time: average
    period: 1hours
  - short_name: [q_gas_E, q_gas_D, q_gas_ED, q_gas_Eup, q_gas_Dup, q_gas_EDup, rhoa, wa, ua]
    period: 1mins
ode_algo: "ARS222"


config: sphere
h_elem: 6 # 550 km
nh_poly: 3
hyperdiff: Hyperdiffusion
rayleigh_sponge: true
viscous_sponge: true
max_newton_iters_ode: 1
