# ARM VARANAL SCM configuration
# Semi-continuous forcing from ARM Variational Analysis product
# Default site: SGP (Southern Great Plains)
initial_condition: "ARMVARANAL"
# Monthly files from: https://adc.arm.gov/discovery/
external_forcing_file: artifact"arm_sgp_varanal_forcing"/sgp60varanarucC1.c1.20100901.000000.cdf
start_date: "20100918" # YYYYMMDD
turbconv: "prognostic_edmfx"
implicit_diffusion: true
approximate_linear_solve_iters: 2
rayleigh_sponge: true
viscous_sponge: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
prognostic_tke: true
microphysics_model: "1M"
config: "column"
hyperdiff: ~
z_max: 15e3 # ARM VARANAL data extends to ~16 km (100 hPa).
z_elem: 45
z_stretch: true
dz_bottom: 30
perturb_initstate: false
dt: "120secs"
dt_rad: "120mins"
t_end: "4days"
ode_algo: "ARS222"
toml: [toml/prognostic_edmfx_varanal_sgp.toml]
rad: allskywithclear
netcdf_output_at_levels: true
netcdf_interpolation_num_points: [2, 2, 60]
output_default_diagnostics: false
diagnostics:
  - short_name: [ts, ta, thetaa, ha, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, hussfc, evspsbl, pr]
    period: 10mins
  - short_name: [arup, waup, taup, thetaaup, haup, husup, hurup, clwup, cliup, waen, taen, thetaaen, haen, husen, huren, clwen, clien, tke]
    period: 10mins
  - short_name: [entr, detr, lmix, bgrad, strain, edt, evu, turbentr]
    period: 10mins
  - short_name: [rlut, rlutcs, rsut, rsutcs, rsdt, rsds, rsus, rlds, rlus, clwvi, lwp, clivi, dsevi, clvi, prw, hurvi, husv, hfss, hfls, clt]
    period: 10mins
