initial_condition: "ReanalysisTimeVarying"
start_date: "20070701"
site_latitude: 17.0
site_longitude: -149.0
turbconv: "prognostic_edmfx"
implicit_diffusion: true
approximate_linear_solve_iters: 2
edmfx_sgsflux_upwinding: first_order
rayleigh_sponge: true
edmfx_entr_model: "PiGroups"
edmfx_detr_model: "Generalized"
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
prognostic_tke: true
microphysics_model: "0M"
config: "column"
z_max: 45e3
z_elem: 200
z_stretch: true
dz_bottom: 30
perturb_initstate: false
dt: "10secs"
dt_rad: "10mins"
t_end: "30hours"
toml: [toml/prognostic_edmfx_calibrated.toml]
netcdf_output_at_levels: true
netcdf_interpolation_num_points: [2, 2, 60]
rad: allskywithclear
ode_algo: "ARS222"
