FLOAT_TYPE: "Float32"
dt_save_state_to_disk: "10days"
dt_save_to_sol: "10days"
dt: "100secs"
t_end: "300days"
h_elem: 16
z_elem: 63
dz_bottom: 30.0
dz_top: 3000.0
z_max: 55000.0
rayleigh_sponge: true
topography: "Earth"
topo_smoothing: true
kappa_4_vorticity: 1.0
kappa_4_scalar: 4.0
divergence_damping_factor: 4.0
moist: "equil"
precip_model: "0M"
surface_setup: "DefaultMoninObukhov"
vert_diff: "FriersonDiffusion"
implicit_diffusion: true
max_newton_iters_ode: 2
rad: "clearsky"
dt_rad: "6hours"
job_id: "longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth"
toml: [toml/longrun_aquaplanet_rhoe_equil_55km_nz63_clearsky_0M_earth.toml]
