agents:
  queue: central
  slurm_mem: 8G
  modules: climacommon/2025_03_18

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  COMMON_CONFIG_PATH: "config/common_configs"
  CONFIG_PATH: "config/model_configs"
  GPU_CONFIG_PATH: "config/gpu_configs"
  PERF_CONFIG_PATH: "config/perf_configs"
  MPI_CONFIG_PATH: "config/mpi_configs"

steps:
  - label: "Initialize"
    retry: &retry_policy
      automatic:
        - exit_status: -1  # Retry on agent lost
          limit: 1
    key: "init_cpu_env"
    concurrency: 1
    concurrency_group: "depot/climaatmos-ci"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate .buildkite"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Prognostic EDMF"
    steps:
      - label: ":genie: Prognostic EDMF: Reproducibility test for deep tropical convection (TRMM)"
        retry: *retry_policy
        command: >
          julia --color=yes --project=.buildkite .buildkite/ci_driver.jl
          --config_file $CONFIG_PATH/prognostic_edmfx_trmm_column.yml
          --job_id prognostic_edmfx_trmm_column

          julia --color=yes --project=.buildkite reproducibility_tests/test_reproducibility.jl
          --job_id prognostic_edmfx_trmm_column
          --out_dir prognostic_edmfx_trmm_column/output_active
        artifact_paths: "prognostic_edmfx_trmm_column/output_active/*"
        agents:
          slurm_mem: 35GB
          slurm_constraint: icelake|cascadelake|skylake|epyc

  - group: "Allocations budget"
    steps:
      - label: ":fire: Allocations budget: Aquaplanet, prognostic EDMF, 1M"
        retry: *retry_policy
        command: >
          julia --color=yes --project=.buildkite perf/flame.jl
          --config_file $COMMON_CONFIG_PATH/numerics_sphere_he16ze63.yml
          --config_file $PERF_CONFIG_PATH/bm_aquaplanet_progedmf_1m.yml
          --job_id flame_aquaplanet_progedmf_1m
        artifact_paths: "flame_aquaplanet_progedmf_1m/*"
        agents:
          slurm_mem: 32GB
