agents:
  queue: central
  slurm_mem: 8G
  modules: climacommon/2025_03_18

env:
  JULIA_LOAD_PATH: "${JULIA_LOAD_PATH}:${BUILDKITE_BUILD_CHECKOUT_PATH}/.buildkite"
  OPENBLAS_NUM_THREADS: 1
  SLURM_KILL_BAD_EXIT: 1
  JULIA_NVTX_CALLBACKS: gc
  JULIA_MAX_NUM_PRECOMPILE_FILES: 100
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/default"
  COMMON_CONFIG_PATH: "config/common_configs"
  CONFIG_PATH: "config/model_configs"
  GPU_CONFIG_PATH: "config/gpu_configs"
  PERF_CONFIG_PATH: "config/perf_configs"
  MPI_CONFIG_PATH: "config/mpi_configs"

steps:
  - label: "Initialize"
    retry: &retry_policy
      automatic:
        - exit_status: -1  # Retry on agent lost
          limit: 1
    key: "init_cpu_env"
    concurrency: 1
    concurrency_group: "depot/climaatmos-ci"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate .buildkite"
      - "julia --project=.buildkite -e 'using Pkg; Pkg.instantiate(;verbose=true); Pkg.precompile(;strict=true); Pkg.status()'"

    agents:
      slurm_cpus_per_task: 8
    env:
      JULIA_NUM_PRECOMPILE_TASKS: 8
      JULIA_MAX_NUM_PRECOMPILE_FILES: 50

  - wait

  - group: "Beres debug"
    steps:
      - label: ":wavy_dash: Beres-c aquaplanet 11yr (memory misalignment debug)"
        retry: *retry_policy
        command: >
          julia --color=yes --project=.buildkite .buildkite/ci_driver.jl
          --config_file $CONFIG_PATH/aquaplanet_beres_c_present_11yr.yml
          --job_id aquaplanet_beres_c_present_11yr
        artifact_paths: "aquaplanet_beres_c_present_11yr/output_active/*"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1
          slurm_mem: 20GB

      - label: ":wavy_dash: Beres NOGW: calibrate alpha"
        retry: *retry_policy
        command: "julia --color=yes --project=.buildkite test/parameterized_tendencies/gravity_wave/non_orographic_gravity_wave/calibrate_beres_alpha.jl"
        env:
          CLIMACOMMS_DEVICE: "CUDA"
        agents:
          slurm_gpus: 1
