"""
    Parameters

Parameter structs for ClimaAtmos and accessors for their values.

The top-level container is `ClimaAtmosParameters`, which holds the
parameters that ClimaAtmos owns directly, together with the parameter sets of
the packages it calls (Thermodynamics, CloudMicrophysics, SurfaceFluxes, RRTMGP,
and Insolation). The structs here are plain, immutable, `isbits` value types, so
they can be captured by GPU kernels; they are built from a ClimaParams TOML
dictionary by the constructors in `create_parameters.jl`.

Every parameter is read through an accessor function of one argument, e.g.
`CAP.planet_radius(params)`, rather than by field access. The accessors are
generated by `@eval` loops at the bottom of this module, one loop per parameter
set, and they all take an `AbstractClimaAtmosParameters`. Three patterns appear:

  - Fields of `ClimaAtmosParameters` itself, forwarded as `ps.\$var`.
  - Fields of a sub-parameter set, forwarded through the accessor of that set,
    e.g. `max_area(ps) = max_area(turbconv_params(ps))`.
  - Parameters owned by another package, forwarded to that package's accessor,
    e.g. `R_d(ps) = TD.Parameters.R_d(thermodynamics_params(ps))`.

The uniform one-argument interface is what lets a tendency ask for a parameter
without knowing which package defines it, and lets parameter sets be swapped
(for calibration, or for a reduced set) without touching call sites.
"""
module Parameters

import ClimaCore as CC
import Insolation.Parameters as IP
import Thermodynamics as TD
import CloudMicrophysics as CM
import SurfaceFluxes as SF

"""
    AbstractClimaAtmosParameters

Supertype of the top-level ClimaAtmos parameter sets, aliased `ACAP`.

Every generated accessor dispatches on this type, so an alternative parameter
container only has to subtype it and provide the sub-parameter-set accessors.
The only concrete subtype is `ClimaAtmosParameters`.
"""
abstract type AbstractClimaAtmosParameters end
const ACAP = AbstractClimaAtmosParameters

"""
    AbstractTurbulenceConvectionParameters

Supertype of the turbulence-convection (PROPHET/EDMF) parameter sets, aliased
`ATCP`. The only concrete subtype is `TurbulenceConvectionParameters`.
"""
abstract type AbstractTurbulenceConvectionParameters end
const ATCP = AbstractTurbulenceConvectionParameters

"""
    AbstractSurfaceTemperatureParameters

Supertype of the prescribed-surface-temperature parameter sets, aliased `ASTP`.
The only concrete subtype is `SurfaceTemperatureParameters`.
"""
abstract type AbstractSurfaceTemperatureParameters end
const ASTP = AbstractSurfaceTemperatureParameters

"""
    AbstractGravityWaveParameters

Supertype of the gravity-wave parameter sets, aliased `AGWP`.

Subtypes:

  - `NonOrographicGravityWaveParameters`: Alexander-Dunkerton spectral
    source and propagation.
  - `OrographicGravityWaveParameters`: Garner topographic drag.
  - `BeresSourceParameters`: Beres convective source for the
    non-orographic scheme.
"""
abstract type AbstractGravityWaveParameters end
const AGWP = AbstractGravityWaveParameters

Base.broadcastable(param_set::ACAP) = tuple(param_set)
Base.broadcastable(param_set::ATCP) = tuple(param_set)
Base.broadcastable(param_set::ASTP) = tuple(param_set)

"""
    TurbulenceConvectionParameters{FT, VFT1, VFT2, VTF3} <: AbstractTurbulenceConvectionParameters

Parameters of the PROPHET (prognostic EDMF) turbulence and convection scheme.

Most values come from ClimaParams; see the `TurbulenceConvectionParameters`
constructor in `create_parameters.jl` for the mapping from ClimaParams names to
the fields below, and for the defaults of the few fields that ClimaParams does
not yet define. `FT` is the float type; `VFT1`, `VFT2`, and `VTF3` are the
`SVector` types of the three data-driven parameter vectors.

# Fields

  - `max_surface_area`: Maximum combined updraft area fraction at the surface,
    reached in the free-convection limit of the surface mass-flux closure [-].
  - `max_area`: Maximum area fraction per updraft [-].
  - `min_area`: Minimum area fraction per updraft [-].
  - `tke_ed_coeff`: TKE diffusivity coefficient `c_m` of the mixing-length
    closure [-].
  - `Ri_crit`: Critical gradient Richardson number [-].
  - `tke_surf_scale`: Ratio of surface-layer TKE to the squared friction
    velocity [-].
  - `tke_surf_flux_coeff`: Coefficient of the flux term in the `u*³` surface TKE
    flux [-].
  - `diagnostic_covariance_coeff`: Prefactor of the turbulent production term in
    the diagnostic covariance closure [-].
  - `sgs_variance_coeff_q`: Coefficient of an optional background SGS total-water
    variance source added to the diagnostic covariance, with standard deviation
    `σ_q = sgs_variance_coeff_q * q_tot` (grid-mean total water). Restores subgrid
    variance where the gradient*mixing-length closure collapses (free troposphere,
    at the mixing-length floor). `0` disables it (default); experimental [-].
  - `sgs_variance_coeff_T`: As `sgs_variance_coeff_q`, for the temperature
    variance, with `σ_T = sgs_variance_coeff_T * T`. `0` disables (default);
    experimental [-].
  - `sgs_variance_coeff_hgrad`: Coefficient of an optional horizontal-gradient
    (scale-similarity / mesoscale) SGS total-water variance source added to the
    diagnostic covariance. It adds a variance proportional to the resolved
    horizontal humidity gradient and the squared grid scale, and so survives
    where turbulence (and the mixing length) collapses in the free troposphere,
    self-targeting fronts and storm tracks. `0` disables it (default);
    experimental [-].
  - `sgs_variance_max_rel_std`: Upper bound on the SGS total-water standard
    deviation relative to the grid-mean total water, `σ_q ≤ sgs_variance_max_rel_std * q_tot`,
    applied when the horizontal-gradient source is active. The 3-point
    Gauss-Hermite quadrature samples `q̂ = q_tot ± √3 σ_q`, so a Gaussian wider than
    `q_tot/√3` puts a node at negative total water; the node is clamped to zero
    without re-weighting, which makes the sampled distribution carry more water
    than the grid mean and can drive the grid-mean vapour negative where the
    resolved horizontal gradient is large next to nearly dry air. `0.5` keeps all
    nodes non-negative (default); experimental [-].
  - `Tq_correlation_coefficient`: Default correlation between `T'` and `q_tot'`
    in the SGS quadrature, in `[-1, 1]` [-].
  - `static_stab_coeff`: Static stability coefficient `c_b` of the mixing-length
    closure [-].
  - `Prandtl_number_scale`: Cospectral budget factor `ω_pr` for the turbulent
    Prandtl number [-].
  - `Prandtl_number_0`: Turbulent Prandtl number in neutral conditions [-].
  - `Pr_max`: Maximum allowed turbulent Prandtl number [-].
  - `smin_ub`: Lower limit of the smooth-minimum function in the mixing-length
    closure [-].
  - `smin_rm`: Upper ratio limit of the smooth-minimum function in the
    mixing-length closure [-].
  - `min_updraft_top`: Minimum updraft height used by the entrainment limiter
    [m].
  - `pressure_normalmode_buoy_coeff1`: Buoyancy coefficient of the perturbation
    pressure closure [-].
  - `pressure_normalmode_drag_coeff`: Drag coefficient of the perturbation
    pressure closure [-].
  - `entr_inv_tau`: Inverse timescale of entrainment [1/s].
  - `entr_inv_length`: Coefficient of the `w` term in the entrainment closure,
    an inverse length scale [1/m].
  - `entr_coeff`: Coefficient of the `w/z` term in the entrainment closure [-].
  - `entr_buoy_coeff`: Coefficient of the `b/w²` term in the entrainment closure
    [-].
  - `entr_detr_buoy_inv_tau_max`: Cap on the inverse buoyancy timescale,
    limiting buoyancy-driven entrainment and detrainment when velocity
    differences become small [1/s].
  - `entr_detr_limit_inv_tau`: Inverse timescale of entrainment and detrainment
    at negligible area fraction [1/s].
  - `detr_inv_tau`: Inverse timescale of detrainment [1/s].
  - `detr_coeff`: Coefficient of the `w` term in the detrainment closure [-].
  - `detr_buoy_coeff`: Coefficient of the `b/w²` term in the detrainment closure
    [-].
  - `detr_vertdiv_coeff`: Coefficient of the vertical-divergence term in the
    detrainment closure [-].
  - `entr_param_vec`: Data-driven entrainment parameter vector [-].
  - `turb_entr_param_vec`: Data-driven turbulent-entrainment parameter vector
    [-].
  - `entr_mult_limiter_coeff`: Exponent of the multiplicative entrainment limiter
    `(1 - a)^c` [-].
  - `detr_massflux_vertdiv_coeff`: Coefficient of the mass-flux
    vertical-divergence term in the detrainment closure [-].
  - `min_area_limiter_scale`: Rate coefficient of the minimum-area limiter in
    entrainment [1/s].
  - `min_area_limiter_power`: Exponent of the minimum-area limiter [-].
  - `max_area_limiter_scale`: Rate coefficient of the maximum-area limiter in
    detrainment [1/s].
  - `max_area_limiter_power`: Exponent of the maximum-area limiter [-].
  - `cloud_fraction_steepness_scale`: Steepness scale `α` of the
    cloud-fraction/condensate relationship; 1 for exact Gaussian or lognormal SGS
    distributions [-].
  - `cloud_fraction_param_vec`: Data-driven cloud-fraction parameter vector [-].
  - `cloud_fraction_eps_rel`: Residual fractional saturation variability
    `ε_rel` in the augmented-`σ` floor of the cloud-fraction closure [-].
  - `cloud_fraction_sigma_abs`: Absolute floor `σ_abs` on the augmented
    saturation-deficit standard deviation [kg/kg].
  - `cloud_fraction_floor_release_margin`: Saturation margin `c_w`, in
    equilibrium PDF widths, at which the relative floor is released [-].
  - `cloud_fraction_floor_release_abs_margin`: Absolute margin `c_a`, in floor
    units, added in quadrature to the release width [-].
  - `cloud_fraction_floor_release_sharpness`: Exponent `s` of the release
    transition; larger values approach a switch [-].
  - `cloud_fraction_floor_residual`: Fraction `D_min` of the relative floor
    retained deep inside a saturated deck [-].
  - `sedimentation_lateral_coeff`: Scaling of the lateral correction in updraft
    sedimentation; 1 is the full correction and 0 disables it [-].
  - `interface_entr_efficiency`: Entrainment efficiency `A` in the interfacial
    entrainment diffusivity `K_e = γ w_e Δz` [-].
  - `sfc_mass_flux_ustar_coeff`: Coefficient `c_u` weighting the
    friction-velocity contribution in the surface mass-flux blend [-].
  - `convective_zi`: Prescribed convective boundary-layer depth `z_i` used in the
    surface mass-flux closure [m].
  - `sfc_mass_flux_cap_fraction`: Fraction `α` of the surface scalar flux that
    the updraft may transport, so the environment retains at least `1 - α` [-].
"""
Base.@kwdef struct TurbulenceConvectionParameters{FT, VFT1, VFT2, VTF3} <: ATCP
    max_surface_area::FT
    max_area::FT
    min_area::FT
    tke_ed_coeff::FT
    Ri_crit::FT
    tke_surf_scale::FT
    tke_surf_flux_coeff::FT
    diagnostic_covariance_coeff::FT
    sgs_variance_coeff_q::FT
    sgs_variance_coeff_T::FT
    sgs_variance_coeff_hgrad::FT
    sgs_variance_max_rel_std::FT
    Tq_correlation_coefficient::FT
    static_stab_coeff::FT
    Prandtl_number_scale::FT
    Prandtl_number_0::FT
    Pr_max::FT
    smin_ub::FT
    smin_rm::FT
    min_updraft_top::FT
    pressure_normalmode_buoy_coeff1::FT
    pressure_normalmode_drag_coeff::FT
    entr_inv_tau::FT
    entr_inv_length::FT
    entr_coeff::FT
    entr_buoy_coeff::FT
    entr_detr_buoy_inv_tau_max::FT
    entr_detr_limit_inv_tau::FT
    detr_inv_tau::FT
    detr_coeff::FT
    detr_buoy_coeff::FT
    detr_vertdiv_coeff::FT
    entr_param_vec::VFT1
    turb_entr_param_vec::VFT2
    entr_mult_limiter_coeff::FT
    detr_massflux_vertdiv_coeff::FT
    min_area_limiter_scale::FT
    min_area_limiter_power::FT
    max_area_limiter_scale::FT
    max_area_limiter_power::FT
    cloud_fraction_steepness_scale::FT
    cloud_fraction_param_vec::VTF3
    cloud_fraction_eps_rel::FT
    cloud_fraction_sigma_abs::FT
    cloud_fraction_floor_release_margin::FT
    cloud_fraction_floor_release_abs_margin::FT
    cloud_fraction_floor_release_sharpness::FT
    cloud_fraction_floor_residual::FT
    # Scaling coefficient for the lateral correction in updraft sedimentation
    sedimentation_lateral_coeff::FT
    interface_entr_efficiency::FT
    # Surface mass flux closure (`set_edmfx_surface_conditions!`).
    sfc_mass_flux_ustar_coeff::FT
    convective_zi::FT
    sfc_mass_flux_cap_fraction::FT
end

"""
    SurfaceTemperatureParameters{FT} <: AbstractSurfaceTemperatureParameters

Parameters of the prescribed analytic sea-surface temperature, following the
RCEMIP protocol.

# Fields

  - `SST_mean`: Mean sea surface temperature [K].
  - `SST_delta`: Peak-to-trough range of the SST sinusoid, i.e. twice its
    amplitude [K].
  - `SST_wavelength`: Wavelength of the SST sinusoid in box geometries [m].
  - `SST_wavelength_latitude`: Wavelength of the SST sinusoid on the sphere
    [degrees latitude].
"""
Base.@kwdef struct SurfaceTemperatureParameters{FT} <: ASTP
    SST_mean::FT
    SST_delta::FT
    SST_wavelength::FT
    SST_wavelength_latitude::FT
end

"""
    NonOrographicGravityWaveParameters{FT} <: AbstractGravityWaveParameters

Parameters of the Alexander-Dunkerton non-orographic gravity-wave
parameterization.

The source spectrum is a Gaussian in phase speed, launched at a fixed pressure
level, with a total momentum flux that varies with latitude. Loaded only when
the scheme is enabled.

# Fields

  - `source_pressure`: Pressure of the wave source level [Pa].
  - `damp_pressure`: Pressure above which the remaining flux is deposited [Pa].
  - `source_height`: Height of the wave source level [m].
  - `Bw`: Spectral amplitude of the broad (westward) wave component [m²/s²].
  - `Bn`: Spectral amplitude of the narrow wave component [m²/s²].
  - `dc`: Phase-speed resolution of the spectral grid [m/s].
  - `cmax`: Maximum phase speed of the spectral grid [m/s].
  - `c0`: Reference phase speed [m/s].
  - `nk`: Number of wave bands [-].
  - `cw`: Phase-speed half-width of the broad component [m/s].
  - `cw_tropics`: Phase-speed half-width of the broad component in the tropics
    [m/s].
  - `cn`: Phase-speed half-width of the narrow component [m/s].
  - `Bt_0`: Background total source momentum flux [Pa].
  - `Bt_n`: Amplitude of the Northern Hemisphere flux enhancement [Pa].
  - `Bt_s`: Amplitude of the Southern Hemisphere flux enhancement [Pa].
  - `Bt_eq`: Amplitude of the equatorial flux enhancement [Pa].
  - `ϕ0_n`: Center latitude of the Northern Hemisphere enhancement [degrees].
  - `ϕ0_s`: Center latitude of the Southern Hemisphere enhancement [degrees].
  - `dϕ_n`: Latitudinal width of the Northern Hemisphere enhancement [degrees].
  - `dϕ_s`: Latitudinal width of the Southern Hemisphere enhancement [degrees].

# Notes

The phase-speed grid is `c[n] = (n - 1) dc - cmax`, so an exact `c = 0` bin
exists only when `cmax / dc` is an integer. The Beres steady source deposits in
that bin and silently does nothing without it.
"""
Base.@kwdef struct NonOrographicGravityWaveParameters{FT} <: AGWP
    source_pressure::FT
    damp_pressure::FT
    source_height::FT
    Bw::FT
    Bn::FT
    dc::FT
    cmax::FT
    c0::FT
    nk::FT
    cw::FT
    cw_tropics::FT
    cn::FT
    Bt_0::FT
    Bt_n::FT
    Bt_s::FT
    Bt_eq::FT
    ϕ0_n::FT
    ϕ0_s::FT
    dϕ_n::FT
    dϕ_s::FT
end

"""
    OrographicGravityWaveParameters{FT} <: AbstractGravityWaveParameters

Parameters of the Garner (2005) orographic gravity-wave drag parameterization.

Subgrid orography in a grid cell is described by a distribution of mountains of
height `h`, whose width scales as `L ∝ h^γ` and whose number density scales as
`n(h) ∝ h^(-ϵ)`. Waves above the critical height `h_crit` propagate and are
handled by the linear drag; the blocked flow below it is handled by the
nonlinear drag. Loaded only when the scheme is enabled.

# Fields

  - `γ`: Mountain height-width exponent in `L ∝ h^γ` [-].
  - `ϵ`: Number-density exponent in `n(h) ∝ h^(-ϵ)` [-].
  - `β`: Mountain shape exponent in `L(z) = L_b (1 - z/h)^β`; 1 is triangular,
    below 1 blunt, above 1 pointy [-].
  - `h_frac`: Height fraction in the blocking threshold `h_crit = h_frac V / N`
    [-].
  - `ρscale`: Density scale factor [-].
  - `L0`: Reference horizontal mountain width [m].
  - `a0`: Coefficient of the propagating (linear) wave drag [-].
  - `a1`: Coefficient of the nonpropagating (blocked) drag [-].
  - `Fr_crit`: Critical Froude number, the nondimensional critical height [-].
"""
Base.@kwdef struct OrographicGravityWaveParameters{FT} <: AGWP
    γ::FT                    # mountain_height_width_exponent: L ∝ h^γ (equation 14, paper suggests γ ≈ 0.4)
    ϵ::FT                    # number_density_exponent: number density of orography in a grid cell, n(h) ∝ h^(-ε)
    β::FT                    # mountain_shape_parameter: L(z) = L_b(1 - z/h)^β (equation 12), β=1 for triangular mountains and β<1 for blunt mountains, β>1 for pointy mountains
    h_frac::FT               # critical_height_threshold: h_crit = h_frac * (V / N), height fraction for blocking threshold
    ρscale::FT               # density_scale_factor: density scale factor for dimensional analysis
    L0::FT                   # reference_mountain_width: L_0 = 80 km, reference horizontal scale
    a0::FT                   # linear_drag_coefficient: a_0 = 0.9, coefficient for propagating wave drag
    a1::FT                   # nonlinear_drag_coefficient: a_1 = 3.0, coefficient for nonpropagating (blocked) drag
    Fr_crit::FT              # critical_froude_number: Fr_crit = 0.7, critical Froude number h̃_c = Fr_crit
end

# Physical/tuning parameters for the Beres (2004) convective gravity-wave source.
"""
    BeresSourceParameters{FT} <: AbstractGravityWaveParameters

Parameters of the Beres (2004) convective source for the non-orographic
gravity-wave scheme.

The source spectrum is obtained by integrating the convective heating spectrum
over frequency, with the heating depth and horizontal cell width setting the
vertical and horizontal wavenumbers. Loaded only when the Beres source is
enabled.

# Fields

  - `Q0_threshold`: Minimum convective heating rate that activates the source
    [K/s].
  - `scale_factor`: Dimensionless amplitude scaling; folds the `ρ₀/(L τ)`
    prefactor, the `|Q_t|²` weight, and empirical tuning into one number [-].
  - `σ_x`: Horizontal half-width of a convective cell [m].
  - `ν_min`: Minimum angular frequency of the frequency integration [rad/s].
  - `ν_max`: Maximum angular frequency of the frequency integration [rad/s].
  - `n_ν`: Number of quadrature points in frequency; must be `4k + 1` for the
    composite Boole's rule [-].
  - `h_heat_min`: Minimum heating depth that activates the source, filtering out
    shallow convection [m].
  - `n_h_avg`: Number of heating depths to average the spectrum over; 1 disables
    averaging and 3 or more smooths the resonance peak [-].
  - `Δh_frac`: Fractional half-range of the heating-depth average, `h ± Δh_frac h`;
    used only when `n_h_avg > 1` [-].
  - `z_bot_floor`: Lowest allowed bottom of the convective heating envelope,
    excluding the boundary-layer turbulence signal [m].
  - `steady_dc_frac`: Weight of the steady DC heating, `Q_t(0)² = steady_dc_frac ν_min`, setting the steady-to-transient amplitude ratio [-].
  - `L_system`: Largest convective-system scale, setting `k_min = 2π / L_system`
    for the steady source [m].
"""
Base.@kwdef struct BeresSourceParameters{FT} <: AGWP
    Q0_threshold::FT         # K/s, minimum heating rate to activate Beres
    scale_factor::FT         # dimensionless amplitude scaling (folds ρ₀/(Lτ), |Q_t|² weight, tuning)
    σ_x::FT                  # m, convective cell horizontal half-width
    ν_min::FT                # 1/s, min frequency (period ~120 min)
    ν_max::FT                # 1/s, max frequency (period ~10 min)
    n_ν::Int                 # quadrature points (must be 4k+1: 5, 9, 13...)
    h_heat_min::FT           # m, minimum heating depth to activate (filters shallow convection)
    n_h_avg::Int             # number of h values to average over (1 = no averaging)
    Δh_frac::FT              # fractional half-range for h averaging: h ± Δh_frac·h
    z_bot_floor::FT          # m, minimum allowed z_bot (excludes PBL turbulence in Q_conv)
    steady_dc_frac::FT       # steady DC heating weight: Q_t(0)² = steady_dc_frac·ν_min
    L_system::FT             # m, largest convective-system scale; sets k_min=2π/L for the steady source
end

"""
    ClimaAtmosParameters{FT, ...} <: AbstractClimaAtmosParameters

Top-level parameter set of a ClimaAtmos simulation.

The first group of fields holds the parameter sets of the packages ClimaAtmos
calls; the rest are the scalar parameters ClimaAtmos owns. Sub-parameter sets
that the configuration does not need are stored as `nothing`, which is why every
one of them has its own type parameter. All parameters are read through the
accessors generated at the bottom of this module, e.g.
`CAP.planet_radius(params)` or `CAP.R_d(params)` for a Thermodynamics parameter.

# Fields

  - `thermodynamics_params`: `Thermodynamics.Parameters.ThermodynamicsParameters`.
  - `rrtmgp_params`: `RRTMGP.Parameters.RRTMGPParameters`.
  - `trace_gas_params`: Fixed volume mixing ratios of the radiatively active trace
    gases [mol/mol].
  - `insolation_params`: `Insolation.Parameters.InsolationParameters`.
  - `microphysics_cloud_params`: Cloud-microphysics parameters: liquid and ice
    properties, terminal-velocity schemes, prescribed droplet number, aerosol
    activation, and the aerosol-ML coefficients.
  - `microphysics_0m_params`: `CloudMicrophysics` 0-moment parameters, or
    `nothing`.
  - `microphysics_1m_params`: `CloudMicrophysics` 1-moment parameters, or
    `nothing`.
  - `microphysics_2m_params`: `CloudMicrophysics` 2-moment warm-rain parameters,
    or `nothing`.
  - `microphysics_2mp3_params`: `CloudMicrophysics` 2-moment plus P3-ice
    parameters, or `nothing`.
  - `surface_fluxes_params`: `SurfaceFluxes.Parameters.SurfaceFluxesParameters`.
  - `turbconv_params`: `TurbulenceConvectionParameters`.
  - `surface_temp_params`: `SurfaceTemperatureParameters`.
  - `vert_diff_params`: Parameters of the simple vertical-diffusion schemes:
    `C_E` [-], and `H` [m] and `D₀` [m²/s] for `DecayWithHeightDiffusion`.
  - `external_forcing_params`: Relaxation timescales [s] and height bounds [m] of
    the GCM-driven forcing.
  - `prescribed_aerosol_params`: Radii [m], hygroscopicities [-], densities
    [kg/m³], and lognormal widths [-] of the prescribed MERRA-2 aerosol modes.
  - `non_orographic_gravity_wave_params`:
    `NonOrographicGravityWaveParameters`, or `nothing`.
  - `orographic_gravity_wave_params`: `OrographicGravityWaveParameters`,
    or `nothing`.
  - `beres_source_params`: `BeresSourceParameters`, or `nothing`.
  - `Omega`: Angular velocity of planetary rotation [rad/s].
  - `f_plane_coriolis_frequency`: Coriolis frequency on an f-plane [1/s].
  - `planet_radius`: Mean radius of the planet [m].
  - `astro_unit`: Astronomical unit [m].
  - `c_smag`: Smagorinsky coefficient [-].
  - `C_H`: Bulk transfer coefficient for sensible heat [-].
  - `ΔT_y_dry`: Equator-to-pole temperature gradient of the dry Held-Suarez
    benchmark [K].
  - `ΔT_y_wet`: Equator-to-pole temperature gradient of the moist Held-Suarez
    benchmark [K].
  - `σ_b`: Vertical extent of the Held-Suarez drag layer, as a fraction of the
    pressure depth [-].
  - `T_equator_dry`: Equatorial temperature of the dry Held-Suarez benchmark [K].
  - `T_equator_wet`: Equatorial temperature of the moist Held-Suarez benchmark
    [K].
  - `T_min_hs`: Minimum temperature of the Held-Suarez relaxation profile [K].
  - `Δθ_z`: Vertical gradient of potential temperature in the Held-Suarez
    relaxation profile [K/m].
  - `alpha_rayleigh_w`: Rayleigh damping coefficient for vertical velocity [1/s].
  - `alpha_rayleigh_uh`: Rayleigh damping coefficient for horizontal velocity
    [1/s].
  - `alpha_rayleigh_tracer`: Rayleigh damping coefficient for tracers [1/s].
  - `zd_viscous`: Height at which viscous sponge damping begins [m].
  - `zd_rayleigh`: Height at which Rayleigh sponge damping begins [m].
  - `kappa_2_sponge`: Viscous sponge coefficient `κ₂` [m²/s].
  - `idealized_ocean_albedo`: Ocean surface albedo for idealized simulations [-].
  - `water_refractive_index`: Refractive index of water relative to air, for the
    broadband ocean-albedo model [-].
  - `constant_horizontal_diffusion_D`: Constant horizontal diffusivity [m²/s].
  - `T_min_sgs`: Lower temperature bound of the SGS quadrature [K].
  - `q_max_sgs`: Upper specific-humidity bound of the SGS quadrature [kg/kg].
  - `fixed_cloud_liquid_terminal_velocity`: Terminal velocity of cloud liquid,
    when a fixed value is used [m/s].
  - `fixed_cloud_ice_terminal_velocity`: Terminal velocity of cloud ice, when a
    fixed value is used [m/s].
  - `fixed_rain_terminal_velocity`: Terminal velocity of rain, when a fixed value
    is used [m/s].
  - `fixed_snow_terminal_velocity`: Terminal velocity of snow, when a fixed value
    is used [m/s].

# Constructor

Built from a ClimaParams TOML dictionary by `ClimaAtmosParameters(toml_dict; ...)` in `create_parameters.jl`, which also decides which sub-parameter sets to
load.
"""
Base.@kwdef struct ClimaAtmosParameters{
    FT,
    TP,
    RP,
    TG,
    IP,
    MPC,
    MP0M,
    MP1M,
    MP2M,
    MP2MP3,
    SFP,
    TCP,
    STP,
    VDP,
    EFP,
    PAP,
    NOGWP,
    OGWP,
    BSP,
} <: ACAP
    thermodynamics_params::TP
    rrtmgp_params::RP
    trace_gas_params::TG
    insolation_params::IP
    microphysics_cloud_params::MPC
    microphysics_0m_params::MP0M
    microphysics_1m_params::MP1M
    microphysics_2m_params::MP2M
    microphysics_2mp3_params::MP2MP3
    surface_fluxes_params::SFP
    turbconv_params::TCP
    surface_temp_params::STP
    vert_diff_params::VDP
    external_forcing_params::EFP
    prescribed_aerosol_params::PAP
    non_orographic_gravity_wave_params::NOGWP
    orographic_gravity_wave_params::OGWP
    beres_source_params::BSP
    Omega::FT
    f_plane_coriolis_frequency::FT
    planet_radius::FT
    astro_unit::FT
    c_smag::FT
    C_H::FT
    # Held Suarez
    ΔT_y_dry::FT
    ΔT_y_wet::FT
    σ_b::FT
    T_equator_dry::FT
    T_equator_wet::FT
    T_min_hs::FT
    Δθ_z::FT
    # Sponge
    alpha_rayleigh_w::FT
    alpha_rayleigh_uh::FT
    alpha_rayleigh_tracer::FT
    zd_viscous::FT
    zd_rayleigh::FT
    kappa_2_sponge::FT
    # Radiation
    idealized_ocean_albedo::FT
    water_refractive_index::FT
    # Constant horizontal diffusion
    constant_horizontal_diffusion_D::FT
    # SGS quadrature bounds
    T_min_sgs::FT
    q_max_sgs::FT
    # Fixed terminal velocities
    fixed_cloud_liquid_terminal_velocity::FT
    fixed_cloud_ice_terminal_velocity::FT
    fixed_rain_terminal_velocity::FT
    fixed_snow_terminal_velocity::FT
end

Base.eltype(::ClimaAtmosParameters{FT}) where {FT} = FT

#####
##### Generated accessors
#####
##### Each loop below defines one accessor per parameter, so that every
##### parameter is reachable as `f(ps)` from the top-level parameter set. The
##### definitions are generated rather than written out because the field lists
##### are long and must not drift from the structs (or from the upstream
##### packages') definitions. To find where a parameter comes from, match its
##### name against the field lists of the structs above and the parameter
##### structs of Thermodynamics, SurfaceFluxes, and Insolation.
#####

# Forward TurbulenceConvection parameters: one accessor taking the top-level
# set, which delegates to one taking the turbconv set.
const TCPS = TurbulenceConvectionParameters
for var in fieldnames(TCPS)
    @eval $var(ps::ACAP) = $var(turbconv_params(ps))
end
for fn in fieldnames(TCPS)
    @eval $(fn)(ps::ATCP) = ps.$(fn)
end

# Forward the Thermodynamics parameters, so that e.g. `CAP.R_d(ps)` works.
for var in fieldnames(TD.Parameters.ThermodynamicsParameters)
    @eval $var(ps::ACAP) = TD.Parameters.$var(thermodynamics_params(ps))
end
# Thermodynamics derived parameters: functions of the fields above rather than
# fields themselves, so they must be listed explicitly.
for var in [:Rv_over_Rd, :kappa_d, :e_int_v0, :e_int_i0, :cv_v, :cv_l, :cv_d]
    @eval $var(ps::ACAP) = TD.Parameters.$var(thermodynamics_params(ps))
end

# Forwarding SurfaceFluxes parameters
"""
    von_karman_const(ps)

Return the von Karman constant from the `SurfaceFluxes` parameter set [-].
"""
von_karman_const(ps::ACAP) =
    SF.Parameters.von_karman_const(surface_fluxes_params(ps))

# ------ MOST (Monin–Obukhov) stability-function coefficients ------

# Insolation parameters
"""
    day(ps)

Return the length of a day from the `Insolation` parameter set [s].
"""
day(ps::ACAP) = IP.day(insolation_params(ps))

"""
    tot_solar_irrad(ps)

Return the total solar irradiance at 1 AU from the `Insolation` parameter set
[W/m²].
"""
tot_solar_irrad(ps::ACAP) = IP.tot_solar_irrad(insolation_params(ps))

# Forward External Forcing parameters
efp_fields = [
    :gcmdriven_momentum_relaxation_timescale,
    :gcmdriven_scalar_relaxation_timescale,
    :gcmdriven_relaxation_minimum_height,
    :gcmdriven_relaxation_maximum_height,
]

for fn_efp in efp_fields
    @eval $(fn_efp)(ps::ACAP) = external_forcing_params(ps).$(fn_efp)
end

# Define the accessors for the fields of ClimaAtmosParameters itself, including
# the sub-parameter sets, which the loops above delegate through.
for var in fieldnames(ClimaAtmosParameters)
    @eval $var(ps::ACAP) = ps.$var
end

end
