#####
##### Apply surface fluxes as boundary conditions and translate them
##### into tendencies for the relevant prognostic variables.
#####

import ClimaCore.Geometry: ⊗
import ClimaCore.Operators as Operators

"""
    boundary_tendency_momentum(ᶜρ, ᶜuₕ, ρ_flux_uₕ_surface)

Return the horizontal-momentum flux divergence generated by the prescribed
surface momentum flux `ρ_flux_uₕ_surface`.

The vertical divergence is built with a zero flux at the top and
`ρ_flux_uₕ_surface` at the bottom, applied to an identically zero interior flux,
so the result is nonzero only in the cell adjacent to the surface. Dividing by
`ᶜρ` turns the `ρuₕ` flux divergence into a `uₕ` tendency. The caller
(`surface_flux_tendency!`) subtracts this from `Yₜ.c.uₕ`, so a positive flux
transfers momentum from the atmosphere to the surface (drag).

# Arguments

  - `ᶜρ`: Cell-center air density [kg/m³].
  - `ᶜuₕ`: Cell-center horizontal velocity; used only for its space and element type
    [m/s].
  - `ρ_flux_uₕ_surface`: Surface flux of horizontal momentum, a
    `ClimaCore.Geometry.AxisTensor` of type `C3 ⊗ C12` [kg/m/s²].

# Returns

A lazy broadcast with the surface-cell contribution to `∂uₕ/∂t` [m/s²].
"""
function boundary_tendency_momentum(ᶜρ, ᶜuₕ, ρ_flux_uₕ_surface)
    FT = eltype(ᶜρ)
    ᶠgradᵥ = Operators.GradientC2F()
    ᶜdivᵥ_uₕ = Operators.DivergenceF2C(
        top = Operators.SetValue(C3(FT(0)) ⊗ C12(FT(0), FT(0))),
        bottom = Operators.SetValue(ρ_flux_uₕ_surface),
    )
    return @. lazy(ᶜdivᵥ_uₕ((0 * ᶠgradᵥ(ᶜuₕ))) / ᶜρ)
end

"""
    boundary_tendency_scalar(ᶜχ, ρ_flux_χ_surface)

Return the flux divergence of the density-weighted scalar `ρχ` generated by the
prescribed surface flux `ρ_flux_χ_surface`.

The vertical divergence is built with a zero flux at the top and
`ρ_flux_χ_surface` at the bottom, applied to an identically zero interior flux, so
the result is nonzero only in the cell adjacent to the surface. The caller
(`surface_flux_tendency!`) subtracts it from the `ρχ` tendency, so a positive flux
(directed from the surface to the atmosphere) is an atmospheric source.

# Arguments

  - `ᶜχ`: Cell-center specific scalar field; used only for its space and element
    type.
  - `ρ_flux_χ_surface`: Surface flux of `ρχ`, a `ClimaCore.Geometry.C3` vector.

# Returns

A lazy broadcast with the surface-cell contribution to `∂(ρχ)/∂t`.
"""
function boundary_tendency_scalar(ᶜχ, ρ_flux_χ_surface)
    FT = eltype(ᶜχ)
    ᶠgradᵥ = Operators.GradientC2F()
    ᶜdivᵥ_χ = Operators.DivergenceF2C(
        top = Operators.SetValue(C3(FT(0))),
        bottom = Operators.SetValue(ρ_flux_χ_surface),
    )
    return @. lazy(ᶜdivᵥ_χ(0 * ᶠgradᵥ(ᶜχ)))
end

"""
    surface_flux_tendency!(Yₜ, Y, p, t)

Add the tendencies from the surface fluxes of momentum, energy, and water.

The fluxes come from `p.precomputed.sfc_conditions` and are turned into
tendencies localized to the surface-adjacent cell by
`boundary_tendency_momentum` and `boundary_tendency_scalar`. Increments:

  - `Yₜ.c.uₕ`, from `sfc_conditions.ρ_flux_uₕ`, unless momentum vertical diffusion
    is disabled.
  - `Yₜ.c.ρe_tot`, from the total-enthalpy flux `sfc_conditions.ρ_flux_h_tot`.
  - `Yₜ.c.ρq_tot` and, with the same increment, `Yₜ.c.ρ`, from
    `sfc_conditions.ρ_flux_q_tot`. All other grid-mean tracers are given a zero
    surface flux here.
  - For `PrognosticEDMFX` (assuming a single updraft), the corresponding `mse` and
    tracer tendencies of `Yₜ.c.sgsʲs.:(1)`, obtained by dividing the grid-mean
    boundary tendency by the updraft density.

Signs follow the flux convention of the boundary-tendency helpers: each term is
subtracted from `Yₜ`, so an upward (surface-to-atmosphere) flux is an atmospheric
source. The whole function returns early when
`p.atmos.disable_surface_flux_tendency` is `true`. Called from
`additional_tendency!`, i.e., treated explicitly. `t` is unused.
"""
function surface_flux_tendency!(Yₜ, Y, p, t)

    p.atmos.disable_surface_flux_tendency && return

    FT = eltype(Y)
    (; params) = p
    (; turbconv_model) = p.atmos
    (; sfc_conditions, ᶜT, ᶜq_liq, ᶜq_ice) = p.precomputed
    thermo_params = CAP.thermodynamics_params(params)

    if !disable_momentum_vertical_diffusion(p.atmos.vertical_diffusion)
        btt = boundary_tendency_momentum(Y.c.ρ, Y.c.uₕ, sfc_conditions.ρ_flux_uₕ)
        @. Yₜ.c.uₕ -= btt
    end

    (; ᶜh_tot) = p.precomputed
    btt = boundary_tendency_scalar(ᶜh_tot, sfc_conditions.ρ_flux_h_tot)
    @. Yₜ.c.ρe_tot -= btt

    if turbconv_model isa PrognosticEDMFX
        # assuming one updraft
        @. Yₜ.c.sgsʲs.:(1).mse -= specific(btt, p.precomputed.ᶜρʲs.:(1))
    end

    ρ_flux_χ = p.scratch.sfc_temp_C3
    foreach_gs_tracer(Yₜ, Y) do ᶜρχₜ, ᶜρχ, ρχ_name
        ᶜχ = @. lazy(specific(ᶜρχ, Y.c.ρ))
        if ρχ_name == @name(ρq_tot)
            @. ρ_flux_χ = sfc_conditions.ρ_flux_q_tot
        else
            @. ρ_flux_χ = C3(FT(0))
        end
        btt = boundary_tendency_scalar(ᶜχ, ρ_flux_χ)
        @. ᶜρχₜ -= btt
        if ρχ_name == @name(ρq_tot)
            @. Yₜ.c.ρ -= btt
        end

        if turbconv_model isa PrognosticEDMFX
            # assuming one updraft
            ᶜχʲₜ = MatrixFields.get_field(Yₜ.c, get_χʲ_name_from_ρχ_name(ρχ_name))
            @. ᶜχʲₜ -= specific(btt, p.precomputed.ᶜρʲs.:(1))
        end
    end
end
