ode_algo: "ARS222"
t_end: "366days"
dt_save_state_to_disk: "1months"
rad: "allskywithclear"
dt_rad: "1hours"
surface_setup: "DefaultMoninObukhov"
turbconv: "prognostic_edmfx"
prognostic_tke: true
edmfx_entr_model: "Generalized"
edmfx_detr_model: "Generalized"
edmfx_nh_pressure: true
edmfx_vertical_diffusion: true
edmfx_filter: true
edmfx_sgs_mass_flux: true
edmfx_sgs_diffusive_flux: true
microphysics_model: "0M"
non_orographic_gravity_wave: true
toml: [toml/hierarchy_toml/sponge.toml, toml/hierarchy_toml/prognostic_edmfx.toml]
