implicit_diffusion: false
approximate_linear_solve_iters: 1
t_end: "366days"
microphysics_model: "0M"
vert_diff: "VerticalDiffusion"
rad: "held_suarez"
dt_save_state_to_disk: "1months"
toml: [toml/hierarchy_toml/sponge.toml]
