diagnostics:
  - short_name: [ta, thetaa, pfull, rhoa, ua, va, wa, hur, hus, cl, clw, cli, husra, hussn]
    period: 10mins
  - short_name: [ts, hfss, hfls, pr, lwp, iwp, rwp, swp]
    period: 10mins
  - short_name: [arup, waup, taup, thetaaup, husup, hurup, clwup, cliup, husraup, hussnup]
    period: 10mins
  - short_name: [husraup, hussnup]
    period: 1hours
    reduction_time: average
  - short_name: [waen, taen, thetaaen, husen, huren, clwen, clien, husraen, hussnen, tke, lmix]
    period: 10mins
  - short_name: [entr, detr, turbentr, bgrad, strain, edt, evu]
    period: 10mins
  - short_name: [
      mp1m_S_phase_change_vap_lcl, mp1m_S_phase_change_vap_icl,
      mp1m_S_acnv_lcl_rai, mp1m_S_acnv_icl_sno,
      mp1m_S_accr_lcl_rai, mp1m_S_accr_lcl_sno_cold, mp1m_S_accr_lcl_sno_warm,
      mp1m_S_accr_melt_lcl_sno,
      mp1m_S_accr_icl_rai, mp1m_S_accr_freeze_icl_rai, mp1m_S_accr_icl_sno,
      mp1m_S_accr_rai_sno_cold, mp1m_S_accr_rai_sno_warm, mp1m_S_accr_melt_rai_sno,
      mp1m_S_phase_change_vap_rai, mp1m_S_phase_change_vap_sno,
      mp1m_S_melt_icl_lcl, mp1m_S_melt_sno_rai,
    ]
    period: 10mins
  - short_name: [
      mp1mup_S_phase_change_vap_lcl, mp1mup_S_phase_change_vap_icl,
      mp1mup_S_acnv_lcl_rai, mp1mup_S_acnv_icl_sno,
      mp1mup_S_accr_lcl_rai, mp1mup_S_accr_lcl_sno_cold, mp1mup_S_accr_lcl_sno_warm,
      mp1mup_S_accr_melt_lcl_sno,
      mp1mup_S_accr_icl_rai, mp1mup_S_accr_freeze_icl_rai, mp1mup_S_accr_icl_sno,
      mp1mup_S_accr_rai_sno_cold, mp1mup_S_accr_rai_sno_warm, mp1mup_S_accr_melt_rai_sno,
      mp1mup_S_phase_change_vap_rai, mp1mup_S_phase_change_vap_sno,
      mp1mup_S_melt_icl_lcl, mp1mup_S_melt_sno_rai,
    ]
    period: 10mins
  - short_name: [
      mp1men_S_phase_change_vap_lcl, mp1men_S_phase_change_vap_icl,
      mp1men_S_acnv_lcl_rai, mp1men_S_acnv_icl_sno,
      mp1men_S_accr_lcl_rai, mp1men_S_accr_lcl_sno_cold, mp1men_S_accr_lcl_sno_warm,
      mp1men_S_accr_melt_lcl_sno,
      mp1men_S_accr_icl_rai, mp1men_S_accr_freeze_icl_rai, mp1men_S_accr_icl_sno,
      mp1men_S_accr_rai_sno_cold, mp1men_S_accr_rai_sno_warm, mp1men_S_accr_melt_rai_sno,
      mp1men_S_phase_change_vap_rai, mp1men_S_phase_change_vap_sno,
      mp1men_S_melt_icl_lcl, mp1men_S_melt_sno_rai,
    ]
    period: 10mins
