#!/usr/bin/env julia

println("climaformat.jl has been discontinued in favor of JuliaFormatter")
println("To use JuliaFormatter, add it to your base environment with: ")
println()
println("    julia -e 'using Pkg; Pkg.add(\"JuliaFormatter\")'")
println()
println("If you already have it in your local environment, you can use")
println()
println("    julia -e 'using JuliaFormatter; format(\".\")'")
println()
println("Then, format your current package with")
println()
println("    using JuliaFormatter; format(\".\")")
println()
println("in a Julia REPL.")
println("See documentation to read more about this change")
println("This file will be removed in future releases")
