name: Downgrade
on:
  pull_request:
  push:
    branches:
      - main
    tags: '*'

# Needed to allow julia-actions/cache to delete old caches that it has created
permissions:
  actions: write
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Downgrade ${{ matrix.version }} - ubuntu-latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.10', '1.11']
    steps:
      - uses: actions/checkout@v6
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-downgrade-compat@v1
        with:
          skip: Artifacts, Dates, Downloads, LazyArtifacts, LinearAlgebra, Logging, Printf, Test, Statistics, Random, Pkg, Glib_jll, Musica

      - uses: julia-actions/julia-buildpkg@latest
      - name: Run infrastructure tests
        uses: julia-actions/julia-runtest@latest
        env:
          TEST_GROUP: infrastructure
      - name: Run diagnostics tests
        uses: julia-actions/julia-runtest@latest
        env:
          TEST_GROUP: diagnostics
      - name: Run dynamics tests
        uses: julia-actions/julia-runtest@latest
        env:
          TEST_GROUP: dynamics
      - name: Run parameterizations tests
        uses: julia-actions/julia-runtest@latest
        env:
          TEST_GROUP: parameterizations
      - name: Run restarts tests
        uses: julia-actions/julia-runtest@latest
        env:
          TEST_GROUP: restarts
      - name: Run era5 tests
        uses: julia-actions/julia-runtest@latest
        env:
          TEST_GROUP: era5
